<Workspace Version="1.2.1.3083" X="-627.106098343377" Y="-664.693078139407" zoom="0.822695359375" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.StringInput guid="93c6c120-575d-46ad-8fa9-17cc16336214" type="CoreNodeModels.Input.StringInput" nickname="String" x="1441.17077242073" y="1116.58566926028" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>ART_Ai depart</System.String>
      <System.String value="ART_Ai depart" />
    </CoreNodeModels.Input.StringInput>
    <CoreNodeModels.Input.StringInput guid="c8d6773b-8a59-409b-8264-72405a770464" type="CoreNodeModels.Input.StringInput" nickname="String" x="1432.61206736836" y="1265.68154051422" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>ART_Ai extremite_NGF</System.String>
      <System.String value="ART_Ai extremite_NGF" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="54e86f5b-5db0-486a-b0fc-a158258a2e1f" type="PythonNodeModels.PythonNode" nickname="SharedParamterFileContent" x="1217.48118896256" y="1323.10130308942" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitUIAPI")

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import Autodesk.Revit.DB.XYZ
import math
import System
from System import Array
from System.Collections.Generic import *

import sys
sys.path.append("C:\\Program Files (x86)\\IronPython 2.7\\Lib\\")
import os
doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application
pp = Autodesk.Revit.ApplicationServices.Application.OpenSharedParameterFile (app)

myGroups = pp.Groups

b = list()
a = list()
for y in myGroups:
    b.append(y.Name)
    for x in y.Definitions:
        a.append(x.Name)
            
#SharedParameterElement.Create(doc, Name='parmaext1',ParameterGroup='G1',ParameterType='Number')

OUT = a
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="5b523ee8-c4cc-45b3-843a-122b34383bbd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1592.54327855566" y="1207.11098935821" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Les entrées effectuées dans ce noeud sont stockées sous forme de liste dans les variables IN.
dataEnteringNode = IN

test=0

for x in IN[0]:
	if x == IN[1] :
		test=1
		break
	else:
		test=0
#Affectez la sortie à la variable OUT.
OUT = test, IN[1]</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="93612df0-3db1-47b0-8939-df67d2e76133" type="CoreNodeModels.Input.StringInput" nickname="String" x="1377.39304050659" y="1527.08853806528" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>ART_Ai extremite</System.String>
      <System.String value="ART_Ai extremite" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="9f260930-10be-47af-8e16-d13d76bd57cc" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1584.10038015775" y="1422.06803227179" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Les entrées effectuées dans ce noeud sont stockées sous forme de liste dans les variables IN.
dataEnteringNode = IN

test=0

for x in IN[0]:
	if x == IN[1] :
		test=1
		break
	else:
		test=0
#Affectez la sortie à la variable OUT.
OUT = test, IN[1]</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.StringInput guid="41f63f2e-4b18-49a0-b52a-bef2f9397f28" type="CoreNodeModels.Input.StringInput" nickname="String" x="1381.76258545897" y="1651.14706278285" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>ART_Ai depart_NGF</System.String>
      <System.String value="ART_Ai depart_NGF" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="34f9c687-f686-4a3a-a799-9ab9a4b9ad37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1585.83485360698" y="1626.39258408685" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Les entrées effectuées dans ce noeud sont stockées sous forme de liste dans les variables IN.
dataEnteringNode = IN

test=0

for x in IN[0]:
	if x.Contains(IN[1]) :
		test=1
		break
	else:
		test=0
#Affectez la sortie à la variable OUT.
OUT = test, IN[1]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="af46ed6a-d334-4824-8698-bf9b4717bb76" type="PythonNodeModels.PythonNode" nickname="Test.SharedParameterInSharedParameterFile" x="1592.73733231995" y="990.850644914124" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Les entrées effectuées dans ce noeud sont stockées sous forme de liste dans les variables IN.
dataEnteringNode = IN

test=0

for x in IN[0]:
	if x == IN[1] :
		test=1
		break
	else:
		test=0
#Affectez la sortie à la variable OUT.
OUT = test, IN[1]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="93c6c120-575d-46ad-8fa9-17cc16336214" start_index="0" end="af46ed6a-d334-4824-8698-bf9b4717bb76" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8d6773b-8a59-409b-8264-72405a770464" start_index="0" end="5b523ee8-c4cc-45b3-843a-122b34383bbd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54e86f5b-5db0-486a-b0fc-a158258a2e1f" start_index="0" end="af46ed6a-d334-4824-8698-bf9b4717bb76" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54e86f5b-5db0-486a-b0fc-a158258a2e1f" start_index="0" end="5b523ee8-c4cc-45b3-843a-122b34383bbd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54e86f5b-5db0-486a-b0fc-a158258a2e1f" start_index="0" end="9f260930-10be-47af-8e16-d13d76bd57cc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54e86f5b-5db0-486a-b0fc-a158258a2e1f" start_index="0" end="34f9c687-f686-4a3a-a799-9ab9a4b9ad37" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93612df0-3db1-47b0-8939-df67d2e76133" start_index="0" end="9f260930-10be-47af-8e16-d13d76bd57cc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="41f63f2e-4b18-49a0-b52a-bef2f9397f28" start_index="0" end="34f9c687-f686-4a3a-a799-9ab9a4b9ad37" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>